apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bend-racing-vehicules-pvc
  namespace: bend-racing-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
